### ISSUE TITLE
its not woeking

### ISSUE THREAD

**Issue by agahahsajhs** [Noroby/OrbWalker#12]
can u try compile this i was compile and inject with extreme injector im holding space but not working pls help

**Comment by Noroby** [comment]
look at my publish

**Comment by agahahsajhs** [comment]
> look at my release

thank u so much u r awsome ur dll is like wadbot better than wadbot<333

**Comment by agahahsajhs** [comment]
who is it focusing on

**Comment by Geronga** [comment]
this is a internal ?

**Comment by Geronga** [comment]
Is it open to development or to making it an internal with evade etc stuff?

**Comment by Noroby** [comment]
it's internal and yes you can redevelop as you like

**Comment by Geronga** [comment]
I don't know c++ but can you help me how to translate what?

**Comment by Geronga** [comment]
I want it to be internal, how do I do it in c#? this

**Comment by Geronga** [comment]
Is there a way to do c# internally I want it to be c# like this, I'm ready to pay $1000 for the codes and if you have a discord, please let me know. or tell me how to do it.

**Comment by Noroby** [comment]
> Is there a way to do c# internally I want it to be c# like this, I'm ready to pay $1000 for the codes and if you have a discord, please let me know. or tell me how to do it.

probably not, because the program needs to be injected into the game as a dll, but C# cannot generate a windows dll but a .net dll.

**Comment by Geronga** [comment]
I understand, is it open to development, will it become a script?

**Comment by Andythem23** [comment]
how to use?
