### ISSUE TITLE
Suggestion: Gui

### ISSUE THREAD

**Issue by LeonardoFBR** [Noroby/OrbWalker#13]
Hi, I really liked the project, would it be possible to add a graphical interface to configure things? I was looking and I was not able to, I'm still learning c++.

**Comment by Noroby** [comment]
I'm not familiar with the gui, please let me know what configuration you want to add and I'll add it when I learned it.

**Comment by LeonardoFBR** [comment]
Could you share your discord with me? If it's not too much trouble.

**Comment by LeonardoFBR** [comment]
Would it be possible to include the function to cast skills?

**Comment by Noroby** [comment]
> Could you share your discord with me? If it's not too much trouble.

i basically don't use discord.

> Would it be possible to include the function to cast skills?

it is indeed possible, but to reduce the risk of being ban, i did not add it. you can learn and add your own code if you need to, because if you're the only one using the code, you basically won't get ban.

**Comment by LeonardoFBR** [comment]
To make the orb more humanized, something like the following could be added:
timer.last_was_move would make the champion's turns more like those of a mouse and not make perfect turns.

	struct Timer
	{
		float last_attack_time{};
		float last_act_time{};
		float last_move_time{};
		float last_was_move{};
	};

	void execute(const Type type) {
		static Timer timer{};
		static bool is_turning_around = false;
		const float now = Functions::GetGameTime();
		if (now < timer.last_act_time + 0.033f) return;
		timer.last_act_time = now;
		if (const auto target = get_target(type); target &&
			(now >= timer.last_attack_time + me->ad() || is_turning_around))
		{
			if (!is_turning_around) timer.last_attack_time = now;
			is_turning_around = true;
			const auto pos = Renderer::WorldToScreen(target->position());
			Functions::IssueOrder(hud_input, 0, 0, 1, pos.x, pos.y, 1);
			if (me->IsFacing(target))
			{
				is_turning_around = false;
				timer.last_move_time = now + me->acd();
			}
		}
		else if (now >= timer.last_move_time && now >= timer.last_was_move + 0.1f)
		{
			timer.last_was_move = now;
			const auto pos = Renderer::WorldToScreen(*mouse_pos);
			Functions::IssueOrder(hud_input, 0, 0, 0, pos.x, pos.y, 0);
		}
	}
}
