### ISSUE TITLE
No Issues, Well Made

### ISSUE THREAD

**Issue by KetamineDev** [Noroby/OrbWalker#14]
Project Works Well, Never Saw Internal Cheats Source Before, Your Coding Styling Is Very Clean.
I've Never Attempted To Work / Make / Build Off, of an Internal Cheat before, thank you for making yours available
I've always made external cheats due to my lack on knowledge when it comes to offsets / patterns / etc, 
(i've only recently started looking into these things), If you'd be willing to teach or even give advice please feel free to respond back

**Comment by KetamineDev** [comment]
Also Suggestion Add Ping Compensation Into The Formula For Waiting Between Attack And Move Commands

**Comment by Noroby** [comment]
Does Ping affect the using experience? I have found that it does not seem to affect functionality.

**Comment by KetamineDev** [comment]
> Does Ping affect the using experience? I have found that it does not seem to affect functionality.

if your ping is stable not so much, however if your ping changes frequently it can cause aa's to cancel I believe.
Also how long do you plan on developing this project?, next update will be big for ADCs

**Comment by KetamineDev** [comment]
Also in your orbwalker.cpp

Object* GetTarget(const Type type) {
    Object* target = nullptr;
    if (type == Type::AutoKite) {
      target = heroes->get_lowest_health(me);
    }
    else if (type == Type::CleanLane) {
      target = minions->get_lowest_health(me);
      if (target == nullptr) {
        target = turrets->get_lowest_health(me);
      }
    }
    else if (type == Type::LastHit) {
      target = minions->get_last_hit(me);
    }
    return target;
  }

you use "get_lowest_health(me)" for  heroes, minions, and turrets. Which
can sometimes cause targeting issues, sorting by nearest seems to be most
effective especially when in group fights

Object* ObjList::get_nearest(Object* const me) const {
    Object* current = nullptr;
    float min_distance = FLT_MAX;
    for (const auto obj : GetObjectList(this)) {
        if (obj->AttackableFor(me)) {
            float distance = obj->DistanceTo(me);
            if (distance < min_distance) {
                min_distance = distance;
                current = obj;
            }
        }
    }
    return current;
}

also switch statements make the getTarget method look much nicer :)

Object* GetTarget(const Type type) {
      Object* target = nullptr;
      switch (type) {
      case Type::AutoKite:
          target = heroes->get_nearest(me);
          break;
      case Type::CleanLane:
          target = minions->get_nearest(me);
          if (target == nullptr) target = turrets->get_nearest(me);
          break;
      case Type::LastHit:
          target = minions->get_last_hit(me);
          break;
      }
      return target;
  }

**Comment by Noroby** [comment]
I will look into Ping. For target selection, you can DIY since it's open source and everyone's needs are different.

**Comment by KetamineDev** [comment]
true targeting is a preference, I haven't been able to figure out how to get accurate ping, tried with an external orbwalker and had to take a screenshot every second and use ocr to read it, and it would still give inaccurate numbers, wish you the best of luck can't wait to see next update 👍

**Comment by KetamineDev** [comment]
> I will look into Ping. For target selection, you can DIY since it's open source and everyone's needs are different.

sorry to bother you again friend, I was wondering if you could possible help me by providing the offset for how to get the targets name, similar to :
float Object::health() const {
	return *(float*)((uintptr_t)this + 0x1068);
}
Also any possible update on the ping address? still working great so far keep up the good work!
