### ISSUE TITLE
Issue with V13.10  Kiero

### ISSUE THREAD

**Issue by Lubrikantas** [Noroby/OrbWalker#18]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1047	The object or library file '..\Kiero\kiero.lib' was created by a different version of the compiler than other objects like 'C:\Users\viliu\Source\Repos\OrbWalker\Release\dllmain.obj'; rebuild all objects and libraries with the same compiler	

what version of the compiler do I need? And how to do it?

**Comment by Noroby** [comment]
Maybe it's because I updated Visual Studio. You can either update your vs to latest version or just download released Hid.dll file.

**Comment by Lubrikantas** [comment]
Ok I will try that, thank you
