### ISSUE TITLE
it is disapper

### ISSUE THREAD

**Issue by Jason1111111** [Noroby/OrbWalker#19]
why it is disapper when i end a game

**Comment by gabep7** [comment]
What disappears specifically?

**Comment by Jason1111111** [comment]
the dll,when i end the game ,it disappered from the folder

**Comment by Jason1111111** [comment]
and it always attact a wrong target ,could you please add a function which is select a target by left click?

**Comment by gabep7** [comment]
Right now the targeting is based on lowest health, change it as you like, the code is open source.

**Comment by Noroby** [comment]
> and it always attact a wrong target ,could you please add a function which is select a target by left click?

you can find ObjectUnderMouse offset at unknowncheat forum.
