### ISSUE TITLE
Hi noroby

### ISSUE THREAD

**Issue by luansilvadb** [Noroby/OrbWalker#21]
Can you tell me what requirements I need to use the source code? I want to learn C development, but I'm having dependency issues when downloading the source code as there are many errors.

**Comment by Noroby** [comment]
The latest version of visual studio, and switch the development environment to x64 Release during development.

**Comment by luansilvadb** [comment]
Hey, it worked! I added the 'std:latest' feature and switched to 'Release' mode, and everything fell into place. I totally missed that info in the README 😅. Thanks a lot for your help! I really appreciate it!
