### ISSUE TITLE
holding spacebar doesnt orbwalk

### ISSUE THREAD

**Issue by Godwius** [Noroby/OrbWalker#23]
ive done as instructed and put the dll inside the game directory with league of legends.exe, started a custom game and when i joined it said noroby orbwalker in the chat, but when i hold spacebar it doesnt orbwalk is there something im doing wrong?
![image](https://github.com/Noroby/OrbWalker/assets/110215340/cf01a2f1-b86b-4316-9641-6fa42d12a7c8)

**Comment by Noroby** [comment]
Are you playing 13.11?  The message in the chat box means it's working. Or you can debug it yourself.
