### ISSUE TITLE
I am unable to use

### ISSUE THREAD

**Issue by yutougua** [Noroby/OrbWalker#28]
On CN, games always end on their own, doesn't it support CN?

**Comment by Noroby** [comment]
马服客户端代码不一样，大概率没法正常工作

**Comment by yutougua** [comment]
wocao，国人。
我自己根据你的代码写了一份，但是
他点击地板的速度实在太快了。
而且大嘴到了3.0的攻速后会空A这是咋回事

**Comment by Noroby** [comment]
时间不准，计算攻速的时候加个十几毫秒的延迟

**Comment by yutougua** [comment]
我试着用你的代码编译出来，点地板的速度也是飞快，这是为啥。
马服会检测点击地板的频率

**Comment by Noroby** [comment]
改一下orbwalker.cpp里的Execute函数的timer.next_action_time = now + milliseconds(33);
时间改大一点就行了

**Comment by yutougua** [comment]
改的差不多了，老哥，这份你有试过在马服玩嘛？或者台服？我主玩马服，我自己的那份全都是外部的，但是多少有点BUG。
想换成你这份，然后我加个自动E跟左键锁敌，想在马服玩。
不过你这份都是调call  马服调call 会不会玩不了多久就被封了？或者台服稳嘛

**Comment by yutougua** [comment]
台服稳定嘛？你用来玩哪个服啊 老哥

**Comment by yutougua** [comment]
托你代码的福，学到了不少。
但是我是通过实体列表遍历整个地图的实体。
我想跟你用Minion  Turret 直接遍历完，这样能去掉好多没用的东西。
但是我不知道例如Minion是怎么用的。单独读的话，他只会一直读一个地址。
我C++不怎么熟，你用的是类我看不太懂
老哥你能跟我说一下，Minion的地址开始，是怎么往下遍历第二个对象遍历到结束的？

**Comment by Noroby** [comment]
用了c++23的新结构span和for循环，可以学一下c++最新知识。
