### ISSUE TITLE
Cant compile it

### ISSUE THREAD

**Issue by jinxx0** [Noroby/OrbWalker#29]
![image](https://github.com/Noroby/OrbWalker/assets/43272857/64d5041e-7aa3-4983-8717-9c03bbdf1912)
![image](https://github.com/Noroby/OrbWalker/assets/43272857/2e2f3b31-dc53-4eaa-8f3d-f3675420d902)

**Comment by jinxx0** [comment]
I need dll file

**Comment by Noroby** [comment]
Uploaded at release page.
