### ISSUE TITLE
Feature Request: Target selector

### ISSUE THREAD

**Issue by jinxx0** [Noroby/OrbWalker#33]

**Comment by gabep7** [comment]
Right now the orbwalker prioritises lowest health champions, you can change it as you would like
https://github.com/Noroby/OrbWalker/blob/9516a6095b9d010d856cae139e15b2abf37633f5/OrbWalker/object.cpp#L68

**Comment by dfcjawx3** [comment]
you know how it would look like ? 
if not get lowest health ? , how would that code look if the target should be like closest to champion? 
ty
