### ISSUE TITLE
LOL Update and Orbwalk Update

### ISSUE THREAD

**Issue by ReyEVRGARDEN** [Noroby/OrbWalker#34]
Hello
I'm new to this business, please tell me what you change after updating in LOL so that orbwalker starts working, only offsets or something else change
I don't speak English and use Google translator, forgive me for that :)

**Comment by Noroby** [comment]
If the game hasn't been updated too much to cause the signature to change, there is no need for an update. However, there are a few offsets that don't use signature, so the offsets need to be updated to version 13.16.

**Comment by dfcjawx3** [comment]
Hey, could you upload the  latest hid.dll ?

**Comment by Noroby** [comment]
Finding offsets requires some disassembly knowledge.
