### ISSUE TITLE
Change Keybinds  , AutoKite Setting 

### ISSUE THREAD

**Issue by dfcjawx3** [Noroby/OrbWalker#36]
Hi , i wanted ask how the Keybinds Can be Changed is it GetAsyncKeyState , if yes in which files does it have to be changed ? 
wanted to change the keybinds 
Could someone upload the hid.dll for 13.16 since i cant compile somehow 

Laneclear X  
autokite on C

**Comment by Noroby** [comment]
In the present function in dllmain.cpp.
