### ISSUE TITLE
Discuss about simulate cast spell

### ISSUE THREAD

**Issue by vacnex** [Noroby/OrbWalker#37]
Hi again, now i have my own base with imgui, orb, drawing, read spell, buffmanager thanks to your source. So I've continued to add cast spell functionality, so I wanted to discuss this with you.

Basically the idea of  simulate cast spell to the target is like this:

1. Pass a key corresponding to the spell to be cast, along with the position of the target determined by its w2s(x,y) coordinates.
2. Use the 'GetCursorPos' function to record the current position of the mouse before moving it to the target's location.
3.  Start pressing the key for the spell.
4. Use the 'SetCursorPos' function to reset the mouse position to the previous coordinate.

```C++
void Mouse::MoveAndPress(HKey key, float x, float y)
{
 
	POINT oldPos;
	GetCursorPos(&oldPos);
	BlockInput(true);
 
	SetCursorPos(x, y);
 
 
	std::this_thread::sleep_for(std::chrono::milliseconds(50));
	Keyboard::PressKey(key);
	std::this_thread::sleep_for(std::chrono::milliseconds(15));
	Keyboard::ReleaseKey(key);
	std::this_thread::sleep_for(std::chrono::milliseconds(50));
 
	SetCursorPos(oldPos.x, oldPos.y);
	BlockInput(false);
}
```

And when i deploy it, it doesn't work as expected, the mouse pointers move indeterminately when i move, and it's also difficult when i move the mouse while orb and cast spell
Check out this video

https://github.com/Noroby/OrbWalker/assets/37587399/f78fafc6-1054-4ce2-94aa-5eb158eac0ff

And my question is
1. I don't know why, can you explain it to me? because basically the idea is correct or am i missing something?
2. Many discussions on UC mention Hook getCurcorPos, which basically implements hook getCurcorPos to interfere with the return value. But I don't know why to do this?
3. I see there are many warnings about using hud castSpell of the game leading to ban, some say that using the wrong function parameters is the cause of the ban, as long as it is used correctly it will be safe. Do you have an opinion on this?

Thank you.

**Comment by dfcjawx3** [comment]
> Hi again, now i have my own base with imgui, orb, drawing, read spell, buffmanager thanks to your source. So I've continued to add cast spell functionality, so I wanted to discuss this with you.
> 
> Basically the idea of simulate cast spell to the target is like this:
> 
> 1. Pass a key corresponding to the spell to be cast, along with the position of the target determined by its w2s(x,y) coordinates.
> 2. Use the 'GetCursorPos' function to record the current position of the mouse before moving it to the target's location.
> 3. Start pressing the key for the spell.
> 4. Use the 'SetCursorPos' function to reset the mouse position to the previous coordinate.
> 
> ```c++
> void Mouse::MoveAndPress(HKey key, float x, float y)
> {
>  
> 	POINT oldPos;
> 	GetCursorPos(&oldPos);
> 	BlockInput(true);
>  
> 	SetCursorPos(x, y);
>  
>  
> 	std::this_thread::sleep_for(std::chrono::milliseconds(50));
> 	Keyboard::PressKey(key);
> 	std::this_thread::sleep_for(std::chrono::milliseconds(15));
> 	Keyboard::ReleaseKey(key);
> 	std::this_thread::sleep_for(std::chrono::milliseconds(50));
>  
> 	SetCursorPos(oldPos.x, oldPos.y);
> 	BlockInput(false);
> }
> ```
> 
> And when i deploy it, it doesn't work as expected, the mouse pointers move indeterminately when i move, and it's also difficult when i move the mouse while orb and cast spell Check out this video
> 
>  pt02hi.mp4 
> And my question is
> 
> 1. I don't know why, can you explain it to me? because basically the idea is correct or am i missing something?
> 2. Many discussions on UC mention Hook getCurcorPos, which basically implements hook getCurcorPos to interfere with the return value. But I don't know why to do this?
> 3. I see there are many warnings about using hud castSpell of the game leading to ban, some say that using the wrong function parameters is the cause of the ban, as long as it is used correctly it will be safe. Do you have an opinion on this?
> 
> Thank you.

Hi , is there  a way to get in Contact with you ? Discord , UC, Zalo , etc. ?

**Comment by Noroby** [comment]
I'm going to use castspell during Zeri's attack, still debugging it and will add it if possible.
