### ISSUE TITLE
CN service sig error

### ISSUE THREAD

**Issue by 553302670** [Noroby/OrbWalker#4]
![屏幕截图 2023-02-15 012647](https://user-images.githubusercontent.com/56016301/218900826-ae7f95dd-52e4-4749-a7fd-17548d7b015f.png)

**Comment by Noroby** [comment]
马服有腾讯自己的东西，特征码未免不同，暂时没有什么办法

**Comment by Kaleo5533** [comment]
> 马服有腾讯自己的东西，特征码未免不同，暂时没有什么办法

soga
