### ISSUE TITLE
target selector

### ISSUE THREAD

**Issue by dejvid52** [Noroby/OrbWalker#40]
when an opponent is reduced to low health orbwalker stops attacking him and changes his target

**Comment by Noroby** [comment]
Right now it will get a different target after each attack, because I can't find a good algorithm to get next right target to attack, especially with Runaan's Hurricane.

**Comment by theg111** [comment]
is not that hard to fix that 
[Current Logic](https://streamable.com/tozhxd)
[Fixed](https://streamable.com/st5k01)

**Comment by jinxx0** [comment]
> is not that hard to fix that [Current Logic](https://streamable.com/tozhxd) [Fixed](https://streamable.com/st5k01)

Where i can get that script?

**Comment by agamagamagam850** [comment]
> > is not that hard to fix that [Current Logic](https://streamable.com/tozhxd) [Fixed](https://streamable.com/st5k01)
> 
> Where i can get that script?

i need that too

**Comment by dejvid52** [comment]
@theg111 can u help me fix this
