### ISSUE TITLE
HeroList seems to be wrong

### ISSUE THREAD

**Issue by LeonardoFBR** [Noroby/OrbWalker#42]
The offset is 0x2192f68 when it should be 0x2192f28.

**Comment by KetamineDev** [comment]
I attempted to get the signatures of both 0x2192f68 and 0x2192f28 and they BOTH return "48 8B 05 ? ? ? ? 4C 8B 78 08" which is the current signature for the HeroList in this Code, however I think it might be a fuck up on league of legends end?, cause Minions and Towers are now being Displayed within the HeroList, and this didn't occur prior to this patch.

**Comment by LeonardoFBR** [comment]
I wanted to ask you something, do you know if the castSpell function has checks ten anticheat?

CastSpell = 0x8af600

**Comment by theg111** [comment]
> I attempted to get the signatures of both 0x2192f68 and 0x2192f28 and they BOTH return "48 8B 05 ? ? ? ? 4C 8B 78 08" which is the current signature for the HeroList in this Code, however I think it might be a fuck up on league of legends end?, cause Minions and Towers are now being Displayed within the HeroList, and this didn't occur prior to this patch.

use 0x2192F28 directly to HeroList, i was facing issue that you comment on uc about all ObjList (minions, turret etc...)
fixed by using 0x2192F28

all good:
https://streamable.com/sfoh6g

**Comment by KetamineDev** [comment]
> > I attempted to get the signatures of both 0x2192f68 and 0x2192f28 and they BOTH return "48 8B 05 ? ? ? ? 4C 8B 78 08" which is the current signature for the HeroList in this Code, however I think it might be a fuck up on league of legends end?, cause Minions and Towers are now being Displayed within the HeroList, and this didn't occur prior to this patch.
> 
> use 0x2192F28 directly to HeroList, i was facing issue that you comment on uc about all ObjList (minions, turret etc...) fixed by using 0x2192F28
> 
> all good: https://streamable.com/sfoh6g

thank you for the advice homie, it works. Idk why I didn't think of that lmfao..... add me on discord if you tryna share some ideas i'm kind of retarded   Discord - thomaz7784
