### ISSUE TITLE
target selector

### ISSUE THREAD

**Issue by eptum** [Noroby/OrbWalker#43]
ignoring a 20% hp target and attacks the full life dude instead

**Comment by KetamineDev** [comment]
Object* ObjList::getLowestHealthTo(Object* const me) const {
    auto targetObjects = GetObjectList(this);
    Object* lowestHealthTarget = nullptr;
    float lowestHealthPercentage = 1.1f; // Initialize with a value greater than 1 to ensure any valid target will be selected

    for (auto targetObject : targetObjects) {
        if (targetObject->attackableFor(me) && targetObject->inRangeOf(me)) {
            float targetHealth = targetObject->health();

            if (targetHealth > 0.0f) {
                // Calculate the target's current health percentage
                float targetHealthPercentage = targetHealth / targetObject->maxHealth();

                // Add more complex conditions as needed
                if (targetHealthPercentage < lowestHealthPercentage) {
                    lowestHealthPercentage = targetHealthPercentage;
                    lowestHealthTarget = targetObject;
                }
            }
        }
    }
    return lowestHealthTarget;
}

**Comment by KetamineDev** [comment]
> ignoring a 20% hp target and attacks the full life dude instead ^ gotchu homie

**Comment by eptum** [comment]
thanks for your help but i do not know how to change it if you could add me in dc and help me my nickname is .eptum

**Comment by theg111** [comment]
if someone need help with target selector, my discord: hundredeleven

https://streamable.com/6vysa9
