### ISSUE TITLE
I want to learn how to update

### ISSUE THREAD

**Issue by python1v9** [Noroby/OrbWalker#55]
I couldn't find where I should enter the offset values. Can I also use it if I only update the offset values?

**Comment by yusufdemyr** [comment]
Yes, i think you can use the program if you update the offset values. You should enter the offset values where memory > offset.hpp. But this program uses patterns ( sigs ) which you should find the patterns and update them.

**Comment by python1v9** [comment]
Is there a program that will help me find patterns?

**Comment by yusufdemyr** [comment]
I don't know how to find patterns but people uses cheat engine. You can search and you can start from here i guess: [Patterns & Patternscanning - Indepth Guide](https://www.unknowncheats.me/forum/league-of-legends/603613-patterns-patternscanning-indepth-guide.html).

Also don't forget to enable `constexpr auto DEBUGMODE = true;` in the offset.hpp. This can help you to find which pattern needs to update.

**Comment by jinxx0** [comment]
> I don't know how to find patterns but people uses cheat engine. You can search and you can start from here i guess: [Patterns & Patternscanning - Indepth Guide](https://www.unknowncheats.me/forum/league-of-legends/603613-patterns-patternscanning-indepth-guide.html).
> 
> Also don't forget to enable `constexpr auto DEBUGMODE = true;` in the offset.hpp. This can help you to find which pattern needs to update.

Kanka kullanıyorsan günceller misin ben yapamadım

**Comment by yusufdemyr** [comment]
Knk bende bilmiyorum güncellemeyi adamın yapmasını bekliyorum 😁

**Comment by jinxx0** [comment]
Pattern değiştirdim ama debug modunu açamadım constexpr auto DEBUGMODE = true; bu kodu tam olarak nereye yazıcam

**Comment by yusufdemyr** [comment]
offset.cpp içinde 69.satırda o kod. Oyuna girince hata olarak messagebox içinde gösteriyordu.

**Comment by M5TTH** [comment]
> Pattern değiştirdim ama debug modunu açamadım constexpr auto DEBUGMODE = true; bu kodu tam olarak nereye yazıcam

13 19 patterni varsa benimle paylaşabilir misin
ben aradım bulamadım

**Comment by afeliss** [comment]
> Pattern değiştirdim ama debug modunu açamadım constexpr auto DEBUGMODE = true; bu kodu tam olarak nereye yazıcam

Sana ulaşabileceğim bir yer var mı ? Dc adresi gibi

**Comment by jinxx0** [comment]
> > Pattern değiştirdim ama debug modunu açamadım constexpr auto DEBUGMODE = true; bu kodu tam olarak nereye yazıcam
> 
> Sana ulaşabileceğim bir yer var mı ? Dc adresi gibi

jinxx9188

**Comment by afeliss** [comment]
> > > Pattern değiştirdim ama debug modunu açamadım constexpr auto DEBUGMODE = true; bu kodu tam olarak nereye yazıcam
> > 
> > 
> > Sana ulaşabileceğim bir yer var mı ? Dc adresi gibi
> 
> jinxx9188

yazdım bu arada ßUŠĘNUR#2847

**Comment by afeliss** [comment]
> I had a few things going on a few points ago, so I didn't update at first time.

Noroby Do you plan to provide training on the update? There are people like me who seriously want to learn and improve :D
