### ISSUE TITLE
hudCastSpell not working and player range render problem

### ISSUE THREAD

**Issue by vacnex** [Noroby/OrbWalker#56]
yo, your hudcastspell is not working, when i pick zeri, q spell not casted when hold space with target champ in range.
when i check in ida i think you call this func.
![image](https://github.com/Noroby/OrbWalker/assets/37587399/6994a33b-63c2-4c83-b913-f8d2e5036adc)
one more problem is your player range render
look this video 

https://github.com/Noroby/OrbWalker/assets/37587399/cebd1ee7-2af3-4c0a-834e-507e2a9bc6ef

**Comment by Noroby** [comment]
I made a small error, which is now fixed.

**Comment by vacnex** [comment]
My base use your hudcastspell and issueorder so  thanks for hard work.
