### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Geronga** [Noroby/OrbWalker#9]
Severity Code Description Project File Line Hide Status
Warning LNK4099 PDB '' not found with 'kiero.lib(kiero.obj)' or on ''; object mounts as if there is no debug information OrbWalker C:\Users\wicke\OneDrive\Desktop\New folder (7)\OrbWalker\kiero.lib(kiero.obj) 1
Warning LNK4099 PDB '' not found with 'kiero.lib(hook.obj)' or on ''; object mounts as if there is no debug information OrbWalker C:\Users\wicke\OneDrive\Desktop\New folder (7)\OrbWalker\kiero.lib(hook.obj) 1
Warning LNK4099 PDB '' not found with 'kiero.lib(trampoline.obj)' or on ''; object mounts as if there is no debug information OrbWalker C:\Users\wicke\OneDrive\Desktop\New folder (7)\OrbWalker\kiero.lib(trampoline.obj) 1
Warning LNK4099 PDB '' not found with 'kiero.lib(buffer.obj)' or on ''; object mounts as if there is no debug information OrbWalker C:\Users\wicke\OneDrive\Desktop\New folder (7)\OrbWalker\kiero.lib(buffer.obj) 1
Warning LNK4099 PDB '' not found with 'kiero.lib(hde64.obj)' or on ''; object mounts as if there is no debug information OrbWalker C:\Users\wicke\OneDrive\Desktop\New folder (7)\OrbWalker\kiero.lib(hde64.obj) 1

**Comment by Noroby** [comment]
try to use /std:c++latest

**Comment by Geronga** [comment]
i am using visual studio 2017 i have no idea what std is

**Comment by Geronga** [comment]
can you help if you have discord
Or can you tell me how to run it in some detail?
I can pay for it.

**Comment by Noroby** [comment]
maybe the vs version is too low, I'm using vs2022 and msvc v143

**Comment by Geronga** [comment]
Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	C1083	Cannot open include file: 'ranges': No such file or directory	OrbWalker	c:\users\wicke\onedrive\masaüstü\yeni klasör (7)\orbwalker	c:\users\wicke\onedrive\masaüstü\yeni klasör (7)\orbwalker\framework.h	11

**Comment by Geronga** [comment]
Cannot open include file: 'ranges': No such file or directory OrbWalker

**Comment by Geronga** [comment]
help pls

**Comment by Geronga** [comment]
Önem Derecesi	Kod	Açıklama	Proje	Dosya	Çizgi	Gizleme Durumu
Hata (etkin)	E0167	"char *" türündeki bağımsız değişken "lm_string_t" türü parametre ile uyumsuz	OrbWalker	C:\Users\wicke\OneDrive\Masaüstü\Yeni klasör (7)\OrbWalker\memory.cpp	35	
Hata (etkin)	E0167	"char *" türündeki bağımsız değişken "lm_string_t" türü parametre ile uyumsuz	OrbWalker	C:\Users\wicke\OneDrive\Masaüstü\Yeni klasör (7)\OrbWalker\memory.cpp	45	
Hata	C2664	'lm_address_t LM_SigScan(lm_string_t,lm_address_t,lm_size_t)' : 1 bağımsız değişkeni '_Elem *' değerinden 'lm_string_t' değerine dönüştürülemez	OrbWalker	C:\Users\wicke\OneDrive\Masaüstü\Yeni klasör (7)\OrbWalker\memory.cpp	35	
Hata	C3536	'address': başlatılmadan önce kullanılamaz	OrbWalker	C:\Users\wicke\OneDrive\Masaüstü\Yeni klasör (7)\OrbWalker\memory.cpp	36	
Hata	C2664	'lm_bool_t LM_FindModule(lm_string_t,lm_module_t *)' : 1 bağımsız değişkeni '_Elem *' değerinden 'lm_string_t' değerine dönüştürülemez	OrbWalker	C:\Users\wicke\OneDrive\Masaüstü\Yeni klasör (7)\OrbWalker\memory.cpp	45

**Comment by Noroby** [comment]
Compile with msvc v143 and /std:latest feature

Build with Release instead of Debug
